before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: UhE/fB3eVm36ypoz5egwpzO49XxInrCFURJnrWQ+sSJYJtW5p7+rvei778/IxsQBssjPh/Md+AS/HUw4/Ul64WPLpU6rrCfd5UHzZyO9SMWK5AbEb6QSLjkGW6fu46H4IdXK/dBEA+10FOT4W1Oe5waWGtAW+wBYhSZk9keJnIrj/rD2+OtW0m8hcSxw9TaT/iHFYPBCA1QEfhKYcuKjFw9wMJR7j2QLpyESvqRsQsL3xpgSs0+1JApZ/fWHi/Ao3T2SfKJDXGU33+G0km9ZcTPKnp+CWcLbOEYElF9ySnCWKM2rqfXtav7tGmftmA4fiXm1LmnNQj4ue2lLF//VjuyUQmzt8ledK9n2bQKEfzJQYZTUuWerYMRKp4pfB2zJ1SEH5G9o/D02TlbYpAoQWE6ftNXKDy+ZH0p+Y8qoBRA18exK5z9qez2eB1WAS8Qiqt5ome/Cuzd/OdiDuStkr1b+WPkngFWwNMBvn4IWvymangC6ZUltUSaXYfKFY0Rx0PIFYKXr/n7BgT8if5WoFTGOZcR0CGFrRHo7QvcesDrGiNAkDopmCO+X+Or0LxV/RpkAn6/+mb2afMoGNUv7AsieS7mzZXBdOeKbQSf15BQ/pdZ+ksvU6tXKh89A8K9HyK2yI7q+48WATECTZa35p550VgHbZNXvcgBI7UXfiKo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
